---
title: "Results"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{output}
  %\VignetteEngine{rmarkdown::render}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval=FALSE
)
```

The CAMDAC pipeline returns a structured directory at the `outdir` from the `CamConfig()` object. The pipeline returns files unique to the RRBS and WGBS modules with the general structure:

```
└── <CamSample.patient_id>
    ├── Allelecounts
    │   ├── <CamSample.id>
    ├── Copynumber
    │   ├── <CamSample.id>
    └── Methylation
        └── <CamSample.id>
```

The sections below describe each results file in more detail. Next, see `vignette("questions")` for frequently asked questions or `vignette("experimental")` for details on experimental CAMDAC features. 

## RRBS pipeline output

```
results/              
└── P                                           
    ├── Allelecounts
    │   ├── N                  
    │   │   └── P.N.SNPs.CpGs.all.sorted.RData
    │   └── T                               
    │       └── P.T.SNPs.CpGs.all.sorted.RData
    ├── Copy_number                             
    │   ├── N                        
    │   │   ├── fragment_length_histogram.pdf      
    │   │   ├── msp1_fragments_RRBS.RData
    │   │   ├── P_N_normal_SNP_data.pdf
    │   │   ├── P.N.SNPs.RData
    │   │   └── Rplots.pdf
    │   └── T
    │       ├── fragment_length_histogram.pdf
    │       ├── msp1_fragments_RRBS.RData
    │       ├── P_T_SNP_data.pdf
    │       ├── P.T.ACF.and.ploidy.txt
    │       ├── P.T.ascat.bc.RData
    │       ├── P.T.ascat.frag.RData
    │       ├── P.T.ascat.output.RData
    │       ├── P.T.ASCATprofile.png
    │       ├── P.T.ASPCF.png
    │       ├── P.T.BAF.PCFed.txt
    │       ├── P.T.germline.png
    │       ├── P.T.LogR.PCFed.txt
    │       ├── P.T.rawprofile.png
    │       ├── P.T.SNPs.RData
    │       ├── P.T.sunrise.png
    │       ├── P.T.tumour.png
    │       └── Rplots.pdf
    └── Methylation
      ├── N
      │   ├── dt_normal_m.RData
      │   └── P_N_methylation_rate_summary.pdf
      └── T
          ├── CAMDAC_DMPs.bed
          ├── CAMDAC_purified_tumour.bed
          ├── CAMDAC_results_per_CpG.RData
          ├── P_T_DMP_stats.txt
          ├── P_T_methylation_rate_summary.pdf
          ├── purified_tumour.RData
          └── tumour_versus_normal_methylomes.pdf  
```

| File | Description |
|------|-------------|
| `P.T.SNPs.CpGs.all.sorted.RData` | Allele counts for a sample. Generated by processing BAM file |
| `P.T.ascat.output.RData` | ASCAT copy number results |
| `P.T.ASCATprofile.png` | ASCAT copy number profile |
| `dt_normal_m.RData` | Bulk normal DNA methylation data |
| `purified_tumour.RData` | CAMDAC-purified DNA methylation rates |
| `CAMDAC_results_per_CpG.fst` | CAMDAC deconvolution and differential methylation results |

## WGBS pipeline output

CAMDAC outputs are written in the directory given by `config$outdir` in the format `PATIENT/DATASET/SAMPLE/`:

```
└── P
    ├── Allelecounts
    │   ├── N
    │   │   └── P.N.SNPs.CpGs.all.sorted.csv.gz
    │   └── T
    │       └── P.T.SNPs.CpGs.all.sorted.csv.gz
    ├── Copynumber
    │   ├── N
    │   │   └── P.N.SNPs.csv.gz
    │   └── T
    │       ├── ascat
    │       ├── battenberg
    │       ├── P.T.cna.txt
    │       ├── P.T.SNPs.csv.gz
    │       └── P.T.tnSNP.csv.gz
    └── Methylation
        ├── N
        │   └── P.N.m.csv.gz
        └── T
            ├── P.T.CAMDAC_annotated_DMRs.fst
            ├── P.T.CAMDAC_results_per_CpG.fst
            ├── P.T.m.csv.gz
            └── P.T.pure.csv.gz
```

| File | Description |
|------|-------------|
| `P.T.SNPs.CpGs.all.sorted.csv.gz` | Allele counts for a sample. Generated by processing BAM file |
| `P.T.SNPs.csv.gz` | SNP counts for a sample. |
| `P.T.cna.txt` | CAMDAC CNA result |
| `P.T.m.csv.gz` | Bulk methylation data |
| `P.T.m.pure.csv.gz` | CAMDAC-deconvolved methylation data |
| `P1.T.CAMDAC_results_per_CpG.fst` | CAMDAC differentially methylated cytosines |
| `P1.T.CAMDAC_annotated_DMRs.fst` | CAMDAC differentially methylated regions |

It is possible to manually override outputs for runs. See `vignette("questions")` for more details.
